version: "2"
linters:
  default: standard
  settings:
    errcheck:
      check-type-assertions: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/o-richard/unpoly-lsp
run:
  allow-parallel-runners: true
